/* This file corresponds to /et9/udbwords/core/udb_words.h revision 1.2 in Tegic CVS, with some minor local changes. */

/*******************************************************************************
;*******************************************************************************
;**                                                                           **
;**                  COPYRIGHT 2006-2009 NUANCE COMMUNICATIONS                **
;**                                                                           **
;**               NUANCE COMMUNICATIONS PROPRIETARY INFORMATION               **
;**                                                                           **
;**     This software is supplied under the terms of a license agreement      **
;**     or non-disclosure agreement with Nuance Communications and may not    **
;**     be copied or disclosed except in accordance with the terms of that    **
;**     agreement.                                                            **
;**                                                                           **
;**                                                                           **
;*******************************************************************************
;**                                                                           **
;**     FileName: udb_words.h                                                 **
;**                                                                           **
;**  Description: For reading out UDB content.                                **
;**                                                                           **
;**                                                                           **
;*******************************************************************************
;******************************************************************************/

#ifndef UDB_WORDS_H
#define UDB_WORDS_H

#include "decumaConfig.h"
#include "et9api.h"


/* don't mangle the function name if compile under C++ */
#if defined(__cplusplus)
extern "C" {
#endif


#ifndef ET9MAXUDBWORDSIZE
#define ET9MAXUDBWORDSIZE    64
#endif


/**
 * The set of available types of word.
 */

typedef enum UDBWORDS_WordType_e {
    UDBWORDS_WordType_RUDB,             /**<  */
    UDBWORDS_WordType_UDB,              /**<  */
    UDBWORDS_WordType_QUDB,             /**<  */

    UDBWORDS_WordType_Last              /**< sentinel */
} UDBWORDS_WordType;

/**
 * A set of actions. The set describes the specific actions available for a record.
 */

typedef struct UDBWORDS_Word_s {
    ET9U16                  wLang;                          /**< . */
    ET9U16                  wFreq;                          /**< . */
    UDBWORDS_WordType       eType;                          /**< . */
    ET9SYMB                 psString[ET9MAXUDBWORDSIZE];    /**< . */
    ET9U16                  wLen;                           /**< . */
} UDBWORDS_Word;

/**
 * Prototype for the function that gets called by the iterator for every word.
 *
 * @param pOwner            Integration specific opaque value passed throuh to the iterator.
 * @param pWord             A UDB word.
 *
 * @return None.
 */

typedef ET9STATUS (*pHandleUdbWord_t)(void *pOwner, const UDBWORDS_Word *pWord);

/**
 * Function to extract all words from an LDB file.
 *
 * @param wLdbNum           LDB number/ID to get words from.
 * @param ET9AWLdbReadData  Callback to get LDB data through (e.g. as generated by the dbmerge tool).
 * @param pOwner            Integration specific opaque value passed throuh to the iterator.
 * @param pWordHandler      Iterator to be called for every word.
 *
 * @return ET9STATUS_NONE on success, otherwise return ET9 error code.
 */

DECUMA_HWR_PRIVATE ET9STATUS UDBWORDS_GetWords (ET9U8               * const pbUdbData,
                             const ET9U16                wUdbDataSize,
                             void                * const pOwner,
                             pHandleUdbWord_t            pWordHandler);


/* End don't mangle the function name if compile under C++ */
#if defined(__cplusplus)
    }
#endif

#endif /* !UDB_WORDS_H */
/* ----------------------------------< eof >--------------------------------- */
